# Generated by Django 4.1 on 2022-08-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacenta',
            name='leader_bacenta',
            field=models.CharField(default='Aucun', max_length=256),
        ),
        migrations.AddField(
            model_name='basonta',
            name='leader_basonta',
            field=models.CharField(default='Aucun', max_length=256),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_membre',
            field=models.IntegerField(max_length=56),
        ),
    ]
