# Generated by Django 4.1 on 2022-08-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0003_alter_membre_bacenta_membre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='berger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='pasteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_membre',
            field=models.IntegerField(),
        ),
    ]
