# Generated by Django 4.1 on 2022-08-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0004_membre_berger_membre_pasteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='berger',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='pasteur',
        ),
    ]
