# Generated by Django 4.1 on 2022-08-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0005_remove_membre_berger_remove_membre_pasteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_branche', models.CharField(max_length=256, unique=True)),
                ('leader_branche', models.CharField(default='Aucun', max_length=256)),
            ],
        ),
    ]
