# Generated by Django 4.1 on 2022-08-14 23:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0008_alter_membre_branche_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='numero_membre',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Basonta_rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('theme', models.CharField(max_length=256)),
                ('offrande', models.PositiveIntegerField()),
                ('date_ajout_rapport', models.DateField(default=datetime.date.today)),
                ('basonta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='basontas_rapport', to='follow_up.basonta')),
            ],
        ),
        migrations.CreateModel(
            name='Bacenta_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('theme', models.CharField(max_length=256)),
                ('offrande', models.PositiveIntegerField()),
                ('date_ajout_rapport', models.DateField(default=datetime.date.today)),
                ('bacenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bacentas_rapport_week', to='follow_up.bacenta')),
            ],
        ),
        migrations.CreateModel(
            name='Bacenta_sunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('date_ajout_rapport', models.DateField(default=datetime.date.today)),
                ('bacenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='basontas_rapport_sunday', to='follow_up.basonta')),
            ],
        ),
    ]
